repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        name: Prettier format check
        files: \.(js|css|html)$
  - repo: local
    hooks:
      - id: spotless-java
        name: Spotless Java Check
        entry: mvn spotless:check
        language: system
        pass_filenames: false
